<application>
  <component name="RecentProjectsManager">
    <option name="recentPaths">
      <list>
        <option value="$USER_HOME$/Desktop/SySafe/1.5.1 prebeta/1.3.1 beta/StocksProject" />
        <option value="$USER_HOME$/Desktop/SySafe/1.5.1 prebeta/1.3.1 beta/EnvironmentClub" />
        <option value="$USER_HOME$/Desktop/SySafe/1.5.1 prebeta/1.3.1 beta/InternalMessagingFinalSchoolProject" />
        <option value="$USER_HOME$/Desktop/SySafe/1.5.1 prebeta/1.3.1 beta/SySafe20" />
        <option value="$USER_HOME$/Desktop/SySafe/1.5.1 prebeta/1.3.1 beta/SySafe_Official" />
        <option value="$USER_HOME$/Desktop/SySafe/1.5.1 prebeta/1.3.1 beta/SySafe_Official - Copy" />
        <option value="$USER_HOME$/Desktop/YoutubeDemo_GoogleMaps/YoutubeDemo_GoogleMaps/YoutubeDemo" />
        <option value="$USER_HOME$/Desktop/YoutubeDemo_GoogleMaps" />
        <option value="$USER_HOME$/Desktop/AttendancePro" />
        <option value="$USER_HOME$/AndroidStudioProjects/InternalMessagingApp" />
        <option value="$USER_HOME$/AndroidStudioProjects/whats_app_clone" />
        <option value="$USER_HOME$/AndroidStudioProjects/ChatApp" />
        <option value="$USER_HOME$/AndroidStudioProjects/firebase-authentication-tutorial" />
        <option value="$USER_HOME$/AndroidStudioProjects" />
        <option value="$USER_HOME$/AndroidStudioProjects/BlogApp" />
        <option value="$USER_HOME$/Desktop/SySafe/1.5.1 prebeta/1.3.1 beta/sysafe" />
        <option value="$USER_HOME$/Desktop/UploadPictureTrialApp" />
        <option value="$USER_HOME$/Desktop/CameraDemo/CameraDemo" />
        <option value="$USER_HOME$/AndroidStudioProjects/CameraFirebaseTrial" />
        <option value="$USER_HOME$/Desktop/SySafe/Releases/1.5.1 prebeta (working)/1.5.1 prebeta (2)/1.3.1 beta/sysafe" />
        <option value="$USER_HOME$/AndroidStudioProjects/SaturdayFinalApp" />
        <option value="$USER_HOME$/Desktop/SySafe/Releases/1.5.1 prebeta (2)/1.3.1 beta/sysafe" />
        <option value="$USER_HOME$/Desktop/S-Assistant2/AttendancePro" />
        <option value="$USER_HOME$/AndroidStudioProjects/firebase-phone-authentication" />
        <option value="$USER_HOME$/AndroidStudioProjects/SySafe" />
        <option value="$USER_HOME$/Desktop/S